[workspace]

members = [
    "cli",
]

[workspace.dependencies]
# https://github.com/bazelbuild/rules_rust/issues/2071
serde = { version = "=1.0.164", features = ["derive"] }
serde_json = "1"
schemars = { version = "0.8" }
