load("@crate_index//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "cli",
    # Specifies the source file for the binary.
    srcs = glob(["src/**"]),
    aliases = aliases(
        normal_dev = True,
        proc_macro = True,
    ),
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    deps = all_crate_deps(
        normal = True,
    ),
)
